### ISSUE TITLE
Ridiculous amounts of debug messages

### ISSUE THREAD

**Issue by Jackiecrazy** [mactso/HarderNaturalHealing#4]
[12:18:52] [Render thread/INFO] [STDOUT/]: [com.mactso.hardernaturalhealing.config.MyConfig:debugMsg:67]: L2:(4219) C xENDx cTim:0 cSat:0.0 cExt:0.5900074 cFod:9.
[12:18:52] [Server thread/INFO] [STDOUT/]: [com.mactso.hardernaturalhealing.config.MyConfig:debugMsg:67]: L2:(6206) S xENDx sTim:0 sSat:0.0 sExt:0.5900074 sFod:9.
[12:18:52] [Render thread/INFO] [STDOUT/]: [com.mactso.hardernaturalhealing.config.MyConfig:debugMsg:67]: L2:(4220) C xENDx cTim:0 cSat:0.0 cExt:0.5900074 cFod:9.

Like so, endlessly. In addition, there's an item use finish debug message every time someone (including the wandering trader) finishes eating/drinking something. My debug level is 0.

**Comment by Darkmega18** [comment]
oh hey again, jackie. so it's not just me going crazy.

**Comment by mactso** [comment]
Sorry- will try to fix this tonight.
Is this for 1.17?

**Comment by mactso** [comment]
This is fixed and pushed as version 6a for minecraft 1.17.1

**Comment by Darkmega18** [comment]
issue. I need it for 1.16.5... D: cause thats what my pack is on.

**Comment by mactso** [comment]
Oh!  I thought I had introduced this as part of my 1.17 conversion.   
Okay- I'll have a 1.16.5 fix out today.

**Comment by mactso** [comment]
The fix is in testing now.   If al goes well, it will be out within the hour.

**Comment by mactso** [comment]
Test is successful; submitting it for approval.

Thanks SO MUCH for the bug report and continued feedback!   It really helps.

Also, since you are using them, If you have any feature/enhancement suggestions I'd love to hear them.

The next planned enhancment to the mob will be command line configuration.
/hardernaturalhealing info
/hardernaturalhealing quickconfig peaceful/easy/hard/hardcore
/hardernaturalhealing minHealth X
/hardernaturalhealing secondsPerHeal X.X
/hardernaturalhealing peaceStarve true/false

This may change slightly duringcoding.

1.16.5 development will continue during 1.18. (and probably 1.19).

**Comment by mactso** [comment]
Okay- it's approved for 1.16

**Comment by Darkmega18** [comment]
thank you a bunch. :)

the command stuff seems interesting. Is this per player or server wide? 

it'd be interesting to be able to have a config for say origins who don't have natural healing and use other mechanics for healing themselves. Although I've resigned it to just "out of combat self restoration" since a lot of healing in my pack needs to be done with bandages and effects etc.

**Comment by mactso** [comment]
Good ideas- non trivial but interesting.  I'd need a command like

/healingClass <playername> <class>

All configuration commands require operator level.

I'm open on whether the "info" command can be used by players or just left as an aid to operators.  Thoughts?

Regarding the last bit...

You can 
a) set the healingPerSecond to be lower (like 0.05)
b) you can set the delay after combat to be higher (1200 would be a minute of peace required)
c) you can raise the minimum hunger for healing to be 19.5 or 20 meatsticks

Tip: Even tho minecraft displays health in increments of a half heart, it tracks it internally at a *very* fine level.   19.488887 is displayed as 9 1/2 hearts while 19.500001 is 10 hearts.  So a low healing rate would create a constant drag on food while not significantly healing the person.

Good luck with your mod pack.  Making ours was a huge push and left me exhausted for weeks afterwards.
