### ISSUE TITLE
Ignores NaturalRegen setting in Minecraft

### ISSUE THREAD

**Issue by rockdemon696** [mactso/HarderNaturalHealing#5]
Minecraft: 1.18.1 Forge: 39.0.64 It ignores NaturalRegen: False. Furthermore it tries to heal even when healingPerSecond is set to 0 in the configs causing hunger to decrease despite no regen occurring.

**Comment by mactso** [comment]
Please provide a pastebin of your configuration file.
Thanks!
MacTso

**Comment by rockdemon696** [comment]
Sorry it took so long to get this. I wasn't at my PC when I noticed the message. https://pastebin.com/RsZgLNGq

**Comment by mactso** [comment]
It's okay.  I had two other issues tonight.   I'll look at this tomorrow.

It might be minecraft is doing it if you are wounded.   

Thanks for the config.  How many hit points was your man at (roughly)?

Cheers,
MacTso

**Comment by mactso** [comment]
Okay so it is currently adding 0.0 extra exhaustion once per second when you are hurt.

This is mostly cosmetic (since it's 0.0) but it is a small performance drain so I can  I can make a change so it doesn't do the operation unless the extra exhaustion is greater than 0.

It's also "healing 0.0 damage" once per second.   I can also add a check for 0 on that so it only runs if the hardernaturalhealing amount is over 0.0.

**Comment by mactso** [comment]
I put in a fix for this but realized later that it is intended to cause extra exhaustion when you are wounded.  So later I'll be putting in a fix that if that is non-zero, it will apply it once per second if you are wounded.  If it is zero it will skip over the code silently.
